// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	model "github.com/manomartins/bitbird/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// DeploymentQueueInterface is an autogenerated mock type for the DeploymentQueueInterface type
type DeploymentQueueInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: data
func (_m *DeploymentQueueInterface) Create(data model.DeploymentQueueModel) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.DeploymentQueueModel) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCardKey provides a mock function with given fields: key
func (_m *DeploymentQueueInterface) GetByCardKey(key string) (*model.DeploymentQueueModel, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetByCardKey")
	}

	var r0 *model.DeploymentQueueModel
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.DeploymentQueueModel, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *model.DeploymentQueueModel); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DeploymentQueueModel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeploymentQueueInterface creates a new instance of DeploymentQueueInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeploymentQueueInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeploymentQueueInterface {
	mock := &DeploymentQueueInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
