version: "3.8"

name: "bitbird-prod"
services:
  app:
    container_name: app
    restart: always
    hostname: app
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile.prod
    ports:
      - "8080:8080"
    networks:
      - my-bridge-network
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ../otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
    networks:
      - my-bridge-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    networks:
      - my-bridge-network

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"  # UI do Jaeger
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    depends_on:
      - otel-collector
    volumes:
      - jaeger_data:/data
    networks:
      - my-bridge-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Você pode personalizar a senha padrão
    restart: unless-stopped
    depends_on:
      - otel-collector
      - prometheus
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    external: true

volumes:
  prometheus_data:
    driver: local
  jaeger_data:
    driver: local
  grafana_data:
    driver: local