version: "3.8"

name: "bitbird-prod"
services:
  app:
    container_name: app
    restart: always
    hostname: app
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile.prod
    ports:
      - "8080:8080"
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    external: true