name: Deploy to OCI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.OCI_SSH_PRIVATE_KEY }}

      - name: Pull latest code on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_HOST }} << 'EOF'
            cd ${{ secrets.OCI_PATH }}
            git pull origin master
          EOF

      - name: Deploy Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_HOST }} << 'EOF'
            cd ${{ secrets.OCI_PATH }}
            cd scripts/
            sudo ./deploy.sh
          EOF
